### ISSUE TITLE
Deprecation of APIs in a pre-1.0 project seems unnecessary

### ISSUE THREAD

**Issue by MateuszKowalewski** [TomasMikula/libretto#89]
I've encountered some `@deprecated` annotations. I don't think it makes sense to put any effort into that currently.

I think at the moment a "move fast and break things" approach would be OK. The whole thing needs to be shaped into something usable and taking care of deprecation policies is imho a waste of time.

I don't think there are so many people out there currently who are trying to use Libretto and could get offended by API breakage. :smile: 

Also, in case this projects uses semantic versioning, breaking stuff is even formally OK pre-1.0.

**Comment by TomasMikula** [comment]
I wouldn't go to great lengths to preserve compatibility with a previous version, but sometimes it is just easy to keep the old API around.

Sometimes, I would even not migrate all code to new version in one go, so there would be parts of Libretto using the deprecated API temporarily.

**Comment by MateuszKowalewski** [comment]
I mean it's currently just noise in the code.

Of course your decision, and it's not wrong what you're doing. Just imho not a good investment of time.

I personally would be more happy about code comments / proper docs instead. Every line of those counts currently!

So instead of deprecation annotations add some even only one-line comment to the new API. This would provide (currently) more value, imho.

**Comment by MateuszKowalewski** [comment]
As this isn't further actionable for anybody else I'm closing this ticket.
